# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile
      env:
        CI: true
    - name: Run ESLint
      run: yarn run lint:es
    - name: Run Stylelint
      run: yarn run lint:stylelint
    - name: Run unit tests
      run: yarn test
    - name: Run Gatsby build
      run: yarn build
      env:
        CI: true
      
  
